import type { Metadata } from "next";
import Link from "next/link";

const PEOPLE: Record<string, { name: string; location: string; intro: string }> = {
  "business-consulting/ashley-bliss": { name: "Ashley Bliss", location: "Batavia, N.Y.", intro: "Agricultural consultant focused on financial analysis, dairy management, business planning and enterprise analysis." },
  "business-consulting/kathryn-canzonier": { name: "Kathryn Canzonier", location: "Burrville, N.Y.", intro: "Experienced agricultural consultant serving farmers across Central and Northern New York." },
  "business-consulting/keith-dickinson": { name: "Keith Dickinson", location: "Northeast", intro: "Business consultant helping agricultural businesses evaluate financial performance and strategic decisions." },
  "business-consulting/rob-goodling": { name: "Rob Goodling", location: "Northeast", intro: "Agricultural business consultant with experience supporting farm financial and management decisions." },
  "business-consulting/michael-hosterman": { name: "Michael Hosterman", location: "Northeast", intro: "Consultant working with diversified agricultural businesses on financial and business planning." },
  "business-consulting/mary-kate-mackenzie": { name: "Mary Kate MacKenzie", location: "Geneva, N.Y.", intro: "Consultant helping agricultural operations with financial analysis and business planning." },
  "business-consulting/gregg-mcconnell": { name: "Gregg McConnell", location: "Cortland, N.Y.", intro: "Regional financial services leader supporting Farm Funding's business consulting programs." },
  "business-consulting/scott-milhollen": { name: "Scott Milhollen", location: "Batavia, N.Y.", intro: "Agricultural consultant with decades of experience across lending and financial services." },
  "business-consulting/emili-ponte": { name: "Emili Ponte", location: "Cooperstown, N.Y.", intro: "Consultant focused on strategic planning and long-term sustainability for agricultural businesses." },
  "business-consulting/ethan-robertson": { name: "Ethan Robertson", location: "Auburn, Maine", intro: "Consultant with experience across dairy, crops, timber, maple and agricultural insurance." },
  "business-consulting/philip-taylor": { name: "Philip Taylor", location: "Cortland, N.Y.", intro: "Agricultural consultant bringing extensive experience in dairy, crops, nutrition and farm financial management." },
  "business-consulting/heather-weeks": { name: "Heather Weeks, CFP®", location: "Bedford, N.H.", intro: "Consultant helping farmers evaluate business growth, financial planning and long-term goals." },
  "business-consulting/rosie-zaginaylo": { name: "Rosie Zaginaylo", location: "Cortland, N.Y.", intro: "Consulting analyst supporting financial analysis, budgets, benchmarking and farm business planning." },
};

const DATA: Record<string, { title: string; intro: string; bullets: string[] }> = {
  "tax-planning-and-prep/farm-funders-tax-preparation-requirements": { title: "Farm Funding Tax Preparation Requirements", intro: "Prepare the information your tax specialist needs so the tax planning and preparation process is efficient and complete.", bullets: ["Organize income and expense records", "Provide required business and asset information", "Keep supporting documentation available", "Discuss major purchases, sales and business changes early"] },
  "tax-planning-and-prep/standards-and-commitment-to-our-customers": { title: "Standards and Commitment to Our Customers", intro: "Our tax professionals follow a structured process designed to provide accurate, timely and agriculture-focused tax service.", bullets: ["Clear communication", "Agricultural tax expertise", "Confidential handling of information", "Year-round planning"] },
  "benchmarking/winery-benchmarks-program": { title: "Winery Benchmarks Program", intro: "A benchmarking program designed to help winery businesses compare financial and operational performance with relevant peers.", bullets: ["Compare key financial measures", "Review production and operating metrics", "Identify strengths and opportunities", "Use results to guide business planning"] },
};
function titleFromSlug(slug: string[]) { return slug.map((part) => part.replace(/\.html$/i, "").replace(/-/g, " ").replace(/\b\w/g, (m) => m.toUpperCase())).join(" / "); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string[] }> }): Promise<Metadata> { const { slug } = await params; const key = slug.join("/"); const p = PEOPLE[key]; const d = DATA[key]; return { title: `${p?.name ?? d?.title ?? titleFromSlug(slug)} | Farm Funding` }; }
export default async function ServicesCatchAll({ params }: { params: Promise<{ slug: string[] }> }) { const { slug } = await params; const key = slug.join("/"); const person = PEOPLE[key]; const d = DATA[key]; const title = person?.name ?? d?.title ?? titleFromSlug(slug); const intro = person?.intro ?? d?.intro ?? "Explore Farm Funding's agricultural service resources and connect with a specialist about your operation."; const bullets = person ? ["Financial analysis", "Business transition planning", "Enterprise analysis", "Expansion planning", "Cost of production analysis", "Succession and estate planning"] : d?.bullets ?? ["Agricultural expertise", "Practical business guidance", "Local support", "Contact your Farm Funding office for details"]; return <main><section className="bg-cream mt-8 px-[4%] py-16 md:py-20"><div className="max-w-6xl mx-auto"><p className="text-xs font-bold uppercase tracking-[0.16em] text-grey-text">Services</p><h1 className="mt-3 font-display text-4xl md:text-[52px] font-extrabold text-forest">{title}</h1>{person && <p className="mt-3 text-sm font-bold text-clay">{person.location}</p>}<p className="mt-5 max-w-3xl text-lg text-charcoal/80 leading-relaxed">{intro}</p></div></section><section className="px-[4%] py-14 md:py-18"><div className="max-w-5xl"><h2 className="font-display text-3xl font-bold text-forest">What to know</h2><ul className="mt-7 list-disc pl-6 space-y-3 text-base text-charcoal/80">{bullets.map((b) => <li key={b}>{b}</li>)}</ul><Link href="/contact" className="mt-8 inline-flex px-7 py-3.5 bg-clay text-white text-sm font-bold rounded-sm">Contact My Office</Link></div></section><section className="bg-forest-dark text-white text-center px-[4%] py-14"><h2 className="font-display text-3xl font-bold text-white">Explore Business Consulting</h2><Link href="/services/business-consulting" className="mt-7 inline-flex px-7 py-3.5 border-2 border-white text-white font-bold rounded-sm">Back to Business Consulting</Link></section></main>; }
