import type { Metadata } from "next";
import Link from "next/link";

const DATA: Record<string, { title: string; intro: string; body: string }> = {
  "Privacy-Statement.html": { title: "Privacy Statement", intro: "Farm Funding respects the privacy of customers and visitors.", body: "This page provides general information about privacy practices, information handling and the choices available to visitors and customers." },
  "Equal-Opportunity-and-Legal.html": { title: "Equal Opportunity & Legal", intro: "Farm Funding is committed to fair and responsible business practices.", body: "Review equal-opportunity information and general legal notices applicable to Farm Funding services." },
  "Terms-of-Use.html": { title: "Terms of Use", intro: "Terms governing use of Farm Funding websites and digital resources.", body: "Please review the current terms before relying on information provided through the site." },
  "Whistleblower.html": { title: "Whistleblower", intro: "Information for reporting suspected misconduct or concerns through appropriate channels.", body: "Farm Funding maintains processes intended to support responsible reporting and appropriate review of concerns." },
  "Portal-Help.html": { title: "Portal Help", intro: "Help for customers using Farm Funding online services.", body: "If you need help accessing a portal or digital service, use the available support options or contact Farm Funding." },
  "Non-Discrimination-Statement.html": { title: "Non-Discrimination Statement", intro: "Farm Funding provides services without unlawful discrimination.", body: "Review the association's current non-discrimination notice and applicable accessibility or equal-opportunity information." },
  "Data-Rights-for-California-Residents.html": { title: "Data Rights for California Residents", intro: "Information about applicable data rights for California residents.", body: "Review the current notice for information about privacy rights and how to exercise them." },
  "Sitemap.html": { title: "Sitemap", intro: "Find major Farm Funding pages and resources in one place.", body: "Use the navigation below to move through financing, services, crop insurance, industries, resources and about pages." },
};

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; return { title: `${DATA[slug]?.title ?? slug.replace(/\.html$/i, "").replace(/-/g, " ")} | Farm Funding` }; }

export default async function EnglishUtilityPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const d = DATA[slug] ?? { title: slug.replace(/\.html$/i, "").replace(/-/g, " "), intro: "Farm Funding information and resources.", body: "Use the links below or contact Farm Funding for assistance." }; return <main><section className="bg-cream mt-8 px-[4%] py-16 md:py-20"><div className="max-w-6xl mx-auto"><p className="text-xs font-bold uppercase tracking-[0.16em] text-grey-text">Farm Funding</p><h1 className="mt-3 font-display text-4xl md:text-[52px] font-extrabold text-forest">{d.title}</h1><p className="mt-5 max-w-3xl text-lg text-charcoal/80 leading-relaxed">{d.intro}</p></div></section><section className="px-[4%] py-14 md:py-18"><div className="max-w-5xl"><p className="text-base text-charcoal/80 leading-relaxed">{d.body}</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/" className="px-6 py-3 bg-clay text-white text-sm font-bold rounded-sm">Home</Link><Link href="/contact" className="px-6 py-3 border-2 border-forest text-forest text-sm font-bold rounded-sm">Contact Us</Link></div></div></section>{slug === "Sitemap.html" && <section className="px-[4%] pb-16"><div className="max-w-6xl grid grid-cols-1 md:grid-cols-3 gap-4">{[["Financing","/financing"],["Services","/services"],["Crop Insurance","/crop-insurance"],["Industries","/industries"],["Resources","/resources"],["About","/about"],["Search","/search"],["Office Locator","/office-locator"],["Member Login","/member-login"]].map(([label, href]) => <Link key={href} href={href} className="border border-line p-5 font-display font-bold text-forest hover:border-clay">{label}</Link>)}</div></section>}</main>; }
