import type { Metadata } from "next";
import Link from "next/link";

const DATA: Record<string, { title: string; intro: string; image?: string; bullets: string[] }> = {
  "products/revenue-protection": { title: "Revenue Protection Crop Insurance", intro: "Revenue Protection combines protection against yield losses with changes in the market price used to value the crop.", image: "/images/crop-insurance/Cash Grain_shutterstock_1153070285.jpg", bullets: ["Protect against qualifying revenue losses", "Choose coverage levels appropriate for the operation", "Work with a crop insurance specialist on deadlines and options"] },
  "products/yield-protection": { title: "Yield Protection & APH Crop Insurance", intro: "Yield Protection is designed around production shortfalls, using your approved yield and the policy's coverage terms.", image: "/images/crop-insurance/Cash Grain_shutterstock_1153070285.jpg", bullets: ["Protection when yields fall below the guarantee", "Coverage built around approved production history", "Specialist guidance through the policy process"] },
  "products/prf": { title: "Pasture, Rangeland & Forage (PRF) Insurance", intro: "PRF insurance can help manage precipitation risk on qualifying grazing and haying acres.", image: "/images/crop-insurance/Beginning-Veteran-Farmer.jpg", bullets: ["Designed for eligible pasture and forage acreage", "Helps manage precipitation risk", "Coverage is based on defined grid and index parameters"] },
  "products/micro-farm": { title: "Micro Farm Policy", intro: "A whole-farm crop insurance option designed for qualifying smaller operations.", image: "/images/crop-insurance/Beginning-Veteran-Farmer.jpg", bullets: ["Whole-farm approach", "Simplified reporting for eligible producers", "Talk with an agent about qualification"] },
  "products/whole-farm-revenue": { title: "Whole Farm Revenue Program", intro: "Whole Farm Revenue Protection can cover revenue from the entire eligible operation under one policy.", image: "/images/crop-insurance/Cash Grain_shutterstock_1153070285.jpg", bullets: ["Whole-operation revenue protection", "Can accommodate diversified farms", "Coverage and eligibility depend on program rules"] },
  "products/crop-hail": { title: "Crop Hail Insurance", intro: "Crop Hail provides protection against hail damage and can complement federal crop insurance coverage.", image: "/images/crop-insurance/Cash Grain_shutterstock_1153070285.jpg", bullets: ["Hail damage protection", "Coverage options vary by crop and location", "Coordinate coverage with your broader risk plan"] },
  "products/margin-protection": { title: "Margin Protection Crop Insurance", intro: "Margin Protection is an area-based plan designed to protect against an unexpected reduction in operating margin.", image: "/images/crop-insurance/Cash Grain_shutterstock_1153070285.jpg", bullets: ["Considers revenue and input-cost changes", "Area-based protection", "Discuss fit with a crop insurance specialist"] },
  "products/sco-eco": { title: "SCO/ECO", intro: "Supplemental Coverage Option and Enhanced Coverage Option can add area-based protection alongside eligible underlying policies.", image: "/images/crop-insurance/Cash Grain_shutterstock_1153070285.jpg", bullets: ["Supplement existing coverage where eligible", "Area-based protection", "Eligibility and deadlines vary by crop and county"] },
  "products/compare": { title: "Compare Federal Crop Insurance Plans – Crop Growers", intro: "Compare common federal crop insurance options and identify the questions to discuss with your agent.", image: "/images/crop-insurance/Insurance-Resources.jpg", bullets: ["Compare coverage purpose", "Review eligibility and deadlines", "Discuss combinations and risk-management goals with an agent"] },
  "dairy-livestock/dairy-revenue-protection": { title: "Dairy Revenue Protection", intro: "Dairy Revenue Protection helps protect against unexpected declines in milk revenue.", image: "/images/crop-insurance/Dairy_Farm Image.jpg", bullets: ["Revenue protection for qualifying dairy production", "Flexible coverage selections", "Specialist support for endorsements and deadlines"] },
  "dairy-livestock/livestock-risk-protection": { title: "Livestock Risk Protection", intro: "Livestock Risk Protection is designed to insure against declines in market price for eligible livestock.", image: "/images/crop-insurance/Dairy_Farm Image.jpg", bullets: ["Market-price protection", "Coverage for eligible cattle and swine", "Work with an agent on timing and coverage"] },
  "dairy-livestock/livestock-gross-margin": { title: "Livestock Gross Margin", intro: "Livestock Gross Margin can protect against a decrease in margin when feed costs rise and livestock prices fall.", image: "/images/crop-insurance/Dairy_Farm Image.jpg", bullets: ["Margin-based protection", "Considers eligible feed and livestock prices", "Review program mechanics with a specialist"] },
  "dairy-livestock/compare": { title: "Dairy Livestock Product Comparison", intro: "Compare dairy and livestock risk-management programs and decide which questions to take to your agent.", image: "/images/crop-insurance/Dairy_Farm Image.jpg", bullets: ["Compare revenue, price and margin protection", "Review eligibility", "Discuss timing and endorsement requirements"] },
  "resources/crop-insurance-deadlines": { title: "Crop Insurance Deadlines", intro: "Important crop insurance dates and deadlines for Northeast producers.", image: "/images/crop-insurance/Insurance-Resources.jpg", bullets: ["Sales closing dates", "Production and acreage reporting", "Endorsement and claim deadlines"] },
  "resources/crop-insurance-specialists": { title: "Crop Insurance Specialists", intro: "Connect with crop insurance professionals who understand Northeast agriculture.", image: "/images/crop-insurance/Insurance-Resources.jpg", bullets: ["Crop and livestock expertise", "Local knowledge", "Risk-management guidance"] },
  "resources/dairy-markets-insights-newsletter": { title: "Dairy Markets Insights Newsletter", intro: "Dairy market information and risk-management insights for producers.", image: "/images/crop-insurance/Dairy_Farm Image.jpg", bullets: ["Market observations", "Risk-management information", "Dairy industry updates"] },
  "resources/young-beginning-small-veteran-farmer-incentives": { title: "Young, Beginning, Small and Veteran Farmer Incentives", intro: "Federal crop insurance rules provide special provisions for qualifying young, beginning, small and veteran producers.", image: "/images/crop-insurance/Beginning-Veteran-Farmer.jpg", bullets: ["Potential administrative-fee benefits", "Additional premium subsidy opportunities", "Eligibility requirements apply"] },
  "resources/producer-responsibilities": { title: "Producer Responsibilities", intro: "Understand the reporting, recordkeeping and policy responsibilities that help keep crop insurance coverage in force.", image: "/images/crop-insurance/Insurance-Resources.jpg", bullets: ["Meet reporting deadlines", "Maintain accurate production records", "Notify your agent promptly about qualifying losses"] },
};

function titleFromSlug(slug: string[]) { return slug.map((part) => part.replace(/\.html$/i, "").replace(/-/g, " ").replace(/\b\w/g, (m) => m.toUpperCase())).join(" / "); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string[] }> }): Promise<Metadata> { const { slug } = await params; const d = DATA[slug.join("/")]; return { title: `${d?.title ?? titleFromSlug(slug)} | Farm Funding` }; }

export default async function CropInsuranceCatchAll({ params }: { params: Promise<{ slug: string[] }> }) {
  const { slug } = await params; const key = slug.join("/"); const d = DATA[key] ?? { title: titleFromSlug(slug), intro: "Explore crop insurance information and resources for Northeast producers.", image: "/images/crop-insurance/Insurance-Resources.jpg", bullets: ["Learn about available coverage", "Review eligibility and deadlines", "Contact an agent for personalized guidance"] };
  return <main>
    <section className="w-full bg-cream mt-8 px-[4%] py-14 md:py-20"><div className="max-w-6xl mx-auto"><p className="text-xs font-bold uppercase tracking-[0.16em] text-grey-text">Crop Insurance</p><h1 className="mt-3 font-display text-4xl md:text-[52px] font-extrabold text-forest">{d.title}</h1><p className="mt-5 max-w-3xl text-base md:text-lg text-charcoal/80 leading-relaxed">{d.intro}</p><Link href="/crop-insurance/agent-finder" className="mt-7 inline-flex px-6 py-3.5 bg-clay text-white text-sm font-bold rounded-sm">Contact an Agent</Link></div></section>
    {d.image && <div className="px-[4%] py-8"><img src={d.image} alt="" className="w-full max-h-[450px] object-cover" /></div>}
    <section className="px-[4%] py-12 md:py-16"><div className="max-w-5xl"><h2 className="font-display text-3xl md:text-4xl font-bold text-forest">What you should know</h2><ul className="mt-7 list-disc pl-6 space-y-3 text-base text-charcoal/80 leading-relaxed">{d.bullets.map((b) => <li key={b}>{b}</li>)}</ul></div></section>
    <section className="bg-forest-dark text-white text-center px-[4%] py-14"><h2 className="font-display text-3xl font-bold text-white">Need help choosing coverage?</h2><p className="mt-4 text-white/85">Talk with a Crop Growers specialist about your operation.</p><Link href="/crop-insurance/agent-finder" className="mt-7 inline-flex px-7 py-3.5 border-2 border-white text-white font-bold rounded-sm hover:bg-white hover:text-forest-dark">Find an Agent</Link></section>
  </main>;
}
