import type { Metadata } from "next";
import Link from "next/link";

const TITLE = "Key Changes Coming to DRP, LGM and LRP Programs: What Producers Need to Know";
const BLOG_PATH = "/resources/todays-harvest-Blog";
const AUTHORS_PATH = "/resources/meet-the-authors";
const ARTICLE_URL = "https://farm-funding.vercel.app/resources/todays-harvest-Blog/260603CG_KeyChangesToDRPandLGMandLRP.html";
const HERO_IMAGE = "/images/industries/Dairy_Farm%20Image-1.jpg";

export const metadata: Metadata = {
  title: `${TITLE} | Farm Funding`,
  description: "Key changes coming to DRP, LGM and LRP programs and what Northeast producers need to know.",
  openGraph: { title: TITLE, description: "Key changes coming to DRP, LGM and LRP programs and what Northeast producers need to know.", url: ARTICLE_URL, type: "article" },
};

const RELATED = [
  { category: "Ag Economy", title: "2025 Northeast Dairy Farm Summary & Mid-Year Outlook", href: "/resources/Industry-Trends-and-Outlooks/Reports/2025NEDairyFarmSummary2026MidYearOutlook", date: "July 10, 2026" },
  { category: "Crop Insurance", title: "USDA Risk Management Agency Announces Emergency Claim Procedures for New York Apple Growers Following Spring Freeze", href: "#", date: "July 8, 2026" },
  { category: "Knowledge Exchange Partner", title: "United States Citizenship and Immigration Service Clears H-2A Path for Dairy Employers", href: "/resources/Industry-Trends-and-Outlooks/Reports/2607KEP_H2AForDairyEmployers.html", date: "July 7, 2026" },
];

const styles = `
.cg-page,.cg-page *{box-sizing:border-box}.cg-page{--clay:#496d83;--clay-dark:#3b5a6d;--forest:#4f832a;--cream:#ecf1e4;--brown:#5a4400;--grey:#686868;--charcoal:#231f20;--line:#d8d8d8;background:#fff;color:var(--charcoal)}
.cg-hero{position:relative;width:100%;height:312px;padding:15px 67px 0;background:var(--clay);color:#fff;overflow:visible}.cg-date{margin:0 0 20px;text-align:right;color:#fff;font:700 14px/1.4 var(--font-montserrat),Montserrat,Arial,sans-serif}.cg-category{display:inline-block;margin:0 0 34px;padding:7px 14px;border:1px solid #fff;color:#fff;text-decoration:none;font:700 14px/1.3 var(--font-montserrat),Montserrat,Arial,sans-serif}.cg-title{max-width:1480px;margin:0;color:var(--cream);font:700 52px/1.12 var(--font-montserrat),Montserrat,Arial,sans-serif;letter-spacing:-.3px}.cg-byline{margin:30px 0 0;color:#fff;font:17px/1.5 var(--font-barlow),Barlow,Arial,sans-serif}.cg-author-link{color:#fff;text-decoration:underline}.cg-hero-image{position:relative;z-index:2;width:min(645px,calc(100% - 40px));height:403px;margin:-37px auto 0;object-fit:cover;display:block}
.cg-copy{width:min(calc(100% - 40px),860px);margin:0 auto;padding:500px 0 20px}.cg-copy p,.cg-copy li{font:400 18px/1.7 var(--font-barlow),Barlow,Arial,sans-serif}.cg-copy p{margin:0 0 24px}.cg-copy h2{margin:38px 0 16px;color:var(--brown);font:700 25px/1.25 var(--font-montserrat),Montserrat,Arial,sans-serif}.cg-copy ul{margin:0 0 24px;padding-left:30px}.cg-copy li{margin-bottom:8px}.cg-copy a{color:var(--clay);text-decoration:underline;text-underline-offset:2px}.cg-contact{text-align:center;padding:10px 0 32px}.cg-button{display:inline-flex;min-height:50px;align-items:center;justify-content:center;padding:13px 28px;background:var(--clay);color:#fff!important;text-decoration:none!important;font:700 16px/1.2 var(--font-montserrat),Montserrat,Arial,sans-serif}.cg-button:hover{background:var(--clay-dark)}
.cg-tags{display:flex;flex-wrap:wrap;align-items:center;gap:6px;width:min(calc(100% - 40px),860px);margin:0 auto;padding:22px 0 28px;border-top:1px solid var(--line);font:16px/1.7 var(--font-barlow),Barlow,Arial,sans-serif}.cg-tags a{color:var(--clay);text-decoration:underline}.cg-tag-icon{width:17px;height:17px;color:var(--brown)}
.cg-author-share{display:grid;grid-template-columns:1fr 1fr;gap:28px;width:min(calc(100% - 40px),1180px);margin:0 auto;padding:20px 0 52px}.cg-box{min-height:176px;padding:22px;background:#f1f3f4}.cg-author-box{display:flex;align-items:center;gap:22px}.cg-author-avatar{width:132px;height:132px;flex:0 0 132px;border-radius:0;background:var(--clay);color:#fff;display:flex;align-items:center;justify-content:center;font:700 42px/1 var(--font-montserrat),Montserrat,Arial,sans-serif}.cg-author-name{color:var(--brown);font:700 21px/1.3 var(--font-montserrat),Montserrat,Arial,sans-serif;text-decoration:underline}.cg-author-role{margin:8px 0 0;font:700 17px/1.4 var(--font-barlow),Barlow,Arial,sans-serif}.cg-share-box{display:flex;align-items:center}.cg-share-label{margin:0 0 16px;font:600 17px/1.4 var(--font-barlow),Barlow,Arial,sans-serif}.cg-share-list{display:flex;gap:10px;margin:0;padding:0;list-style:none}.cg-share-list a{display:inline-flex;width:42px;height:42px;align-items:center;justify-content:center;border-radius:4px;color:#fff;text-decoration:none}.cg-share-list svg{width:22px;height:22px}.cg-x{background:#14171a}.cg-fb{background:#1877f2}.cg-li{background:#0a66c2}.cg-mail{background:#34a853}
.cg-related-wrap{background:var(--cream)}.cg-related{width:min(calc(100% - 40px),1180px);margin:0 auto;padding:34px 0 54px}.cg-section-title{margin:0;color:var(--brown);font:700 30px/1.25 var(--font-montserrat),Montserrat,Arial,sans-serif}.cg-related-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:34px;margin-top:20px}.cg-related-card{padding-top:26px}.cg-related-category{display:inline-block;padding:6px 14px;background:#686868;color:#fff;font:700 13px/1.2 var(--font-barlow),Barlow,Arial,sans-serif;letter-spacing:.02em;text-transform:uppercase;text-decoration:none}.cg-related-title{display:block;margin-top:26px;color:var(--brown);font:700 21px/1.35 var(--font-montserrat),Montserrat,Arial,sans-serif;text-decoration:none}.cg-related-date{margin:26px 0 0;color:var(--grey);font:700 14px/1.3 var(--font-barlow),Barlow,Arial,sans-serif;text-transform:uppercase}
.cg-authors{display:grid;grid-template-columns:minmax(0,2fr) minmax(240px,1fr);align-items:center;gap:28px;width:min(calc(100% - 40px),1180px);margin:0 auto;padding:50px 0}.cg-authors-text{max-width:900px;margin:14px 0 0;font:20px/1.5 var(--font-barlow),Barlow,Arial,sans-serif}.cg-authors-button{justify-self:end;min-width:205px}.cg-newsletter{padding:60px 20px;background:var(--forest);color:#fff;text-align:center}.cg-newsletter h2{margin:0;color:#fff;font:700 44px/1.15 var(--font-montserrat),Montserrat,Arial,sans-serif}.cg-newsletter p{margin:22px 0 0;font:500 21px/1.4 var(--font-barlow),Barlow,Arial,sans-serif}.cg-form{display:flex;justify-content:center;align-items:flex-end;gap:10px;margin-top:30px}.cg-group{text-align:left}.cg-label{display:block;margin-bottom:9px;font:700 18px/1.3 var(--font-barlow),Barlow,Arial,sans-serif}.cg-email{width:245px;height:44px;border:0;border-radius:2px;padding:0 13px;font:17px var(--font-barlow),Barlow,Arial,sans-serif}.cg-required{margin-top:8px;font:italic 14px var(--font-barlow),Barlow,Arial,sans-serif}.cg-signup{height:44px;min-width:112px;border:2px solid #fff;border-radius:4px;background:var(--forest);color:#fff;font:700 18px var(--font-barlow),Barlow,Arial,sans-serif}
@media(max-width:991px){.cg-hero{height:auto;padding:22px 28px 38px}.cg-title{font-size:45px}.cg-hero-image{margin:20px auto 0;width:calc(100% - 56px);height:auto;aspect-ratio:645/403}.cg-copy{padding-top:60px;width:calc(100% - 56px)}.cg-tags,.cg-author-share,.cg-related,.cg-authors{width:calc(100% - 56px)}.cg-related-grid{grid-template-columns:repeat(2,1fr)}}
@media(max-width:767px){.cg-hero{padding:20px 16px 24px}.cg-date{text-align:left}.cg-category{margin-bottom:20px}.cg-title{font-size:35px}.cg-byline{font-size:16px;margin-top:18px}.cg-hero-image{width:calc(100% - 28px);height:230px;aspect-ratio:auto}.cg-copy{width:calc(100% - 28px);padding-top:34px}.cg-copy p,.cg-copy li{font-size:17px;line-height:1.72}.cg-copy h2{font-size:23px}.cg-tags,.cg-author-share,.cg-related,.cg-authors{width:calc(100% - 28px)}.cg-author-share{grid-template-columns:1fr;gap:18px}.cg-box{min-height:0}.cg-author-box{align-items:flex-start}.cg-author-avatar{width:96px;height:96px;flex-basis:96px;font-size:30px}.cg-related{padding-top:25px;padding-bottom:35px}.cg-section-title{font-size:27px}.cg-related-grid{grid-template-columns:1fr;gap:25px}.cg-related-title{font-size:20px}.cg-authors{grid-template-columns:1fr;gap:18px;padding:38px 0}.cg-authors-button{justify-self:start}.cg-newsletter{padding:48px 14px 52px}.cg-newsletter h2{font-size:31px}.cg-newsletter p{font-size:17px}.cg-form{flex-direction:column;align-items:stretch}.cg-email,.cg-signup{width:100%}}
`;

export default function DRPLGMLRPArticle(){
  const shareUrl=encodeURIComponent(ARTICLE_URL), shareText=encodeURIComponent(TITLE);
  return <><style dangerouslySetInnerHTML={{__html:styles}}/><main className="cg-page">
    <section className="cg-hero">
      <p className="cg-date">June 3, 2026</p>
      <Link href={`${BLOG_PATH}?category=crop-insurance`} className="cg-category">Crop Insurance</Link>
      <h1 className="cg-title">{TITLE}</h1>
      <p className="cg-byline">By: <Link href={`${AUTHORS_PATH}#Megan-Clancy`} className="cg-author-link">Megan Clancy</Link></p>
    </section>
    <img className="cg-hero-image" src={HERO_IMAGE} alt="Dairy farm" />
    <article className="cg-copy">
      <p>The USDA Risk Management Agency (RMA) recently announced several updates to Dairy Revenue Protection (DRP), Livestock Gross Margin (LGM) and Livestock Risk Protection (LRP) programs that will take effect beginning with the 2027 crop year on July 1, 2026. The changes are intended to improve flexibility, expand coverage opportunities and create more consistency across livestock insurance products.</p>
      <h2>Uniform Changes Across Programs</h2>
      <p>Several updates will apply across DRP, LGM and LRP, including:</p>
      <ul><li>Updated subsidies for beginning farmers and ranchers, providing more affordable insurance coverage.</li><li>Offering concurrent coverage, enabling producers to use multiple livestock programs together.</li><li>Producers must utilize the policy and add coverage otherwise the policy will be automatically canceled if it isn&apos;t used for three years.</li></ul>
      <h2>DRP Updates</h2>
      <p>DRP sales periods will now extend through the following calendar day to better align with other livestock insurance programs. This means that producers can no longer add coverage on Sunday morning. The deadline to add coverage will be Saturday.</p>
      <h2>LGM Changes</h2>
      <p>Several updates were made to LGM coverage, including:</p>
      <ul><li>Increasing the maximum cattle weight to 1,800 pounds</li><li>Increasing feeder cattle target weights from 9 to 12 cwt for yearling finishing operations</li><li>Increasing live cattle target weights for both yearling and calf finishing operations</li><li>Clarifying ownership requirements for covered cattle</li></ul>
      <p>These changes better reflect today’s cattle feeding practices and provide additional flexibility for producers.</p>
      <h2>Updates to LRP Coverage</h2>
      <p>Key LRP updates include:</p>
      <ul><li>Additional forage disaster exemption guidelines for drought and natural disasters</li><li>Increased maximum weights for Fed Cattle types</li><li>Expansion of Cull Cow coverage up to 52 weeks</li><li>Added new unborn feeder cattle categories, creating additional coverage options for producers</li></ul>
      <h2>What This Means for Producers</h2>
      <p>These updates continue to modernize dairy and livestock insurance programs and provide producers with additional flexibility and opportunities to manage today’s volatile dairy and livestock markets. As always, evaluating risk management opportunities and understanding available coverage options remain important parts of protecting profitability.</p>
      <p>Updated 2027 handbooks and policy documents can be found on the <a href="https://www.rma.usda.gov/">USDA RMA Livestock Insurance Plans website</a>.</p>
      <p>Contact your Dairy &amp; Livestock Risk Management agent to learn more about how these updates may impact your operation and overall risk management strategy.</p>
      <div className="cg-contact"><p>To learn more about a customized risk management strategy, contact the Crop Growers team at livestock@cropgrowers.com.</p><Link href="#contact-crop-growers" className="cg-button">Contact Crop Growers</Link></div>
    </article>
    <div className="cg-tags"><svg className="cg-tag-icon" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M21.41 11.58l-9-9C12.05 2.22 11.55 2 11 2H4c-1.1 0-2 .9-2 2v7c0 .55.22 1.05.59 1.41l9 9c.36.36.86.36 1.41.59.55-.23 1.41-.59 1.41-1.41l7-7c.37-.36.59-.86.59-1.41 0-.55-.22-1.06-.59-1.42zM6.5 8C5.67 8 5 7.33 5 6.5S5.67 5 6.5 5 8 5.67 8 6.5 7.33 8 6.5 8z"/></svg><span>Tags:</span> <Link href={`${BLOG_PATH}?tag=crop-insurance`}>crop insurance</Link>, <Link href={`${BLOG_PATH}?tag=dairy`}>dairy</Link>, <Link href={`${BLOG_PATH}?tag=livestock`}>livestock</Link>, <Link href={`${BLOG_PATH}?tag=risk-management`}>risk management</Link></div>
    <div className="cg-author-share">
      <div className="cg-box cg-author-box"><div className="cg-author-avatar">MC</div><div><Link href={`${AUTHORS_PATH}#Megan-Clancy`} className="cg-author-name">Megan Clancy</Link><p className="cg-author-role">Livestock Insurance Specialist</p></div></div>
      <div className="cg-box cg-share-box"><div><p className="cg-share-label">Share this post on</p><ul className="cg-share-list"><li><a className="cg-x" href={`https://twitter.com/share?text=${shareText}&url=${shareUrl}`} target="_blank" rel="noreferrer" aria-label="Share on X">X</a></li><li><a className="cg-fb" href={`https://www.facebook.com/sharer/sharer.php?u=${shareUrl}`} target="_blank" rel="noreferrer" aria-label="Share on Facebook">f</a></li><li><a className="cg-li" href={`https://www.linkedin.com/shareArticle?url=${shareUrl}&title=${shareText}`} target="_blank" rel="noreferrer" aria-label="Share on LinkedIn">in</a></li><li><a className="cg-mail" href={`mailto:?subject=${shareText}&body=${shareUrl}`} aria-label="Share by email">@</a></li></ul></div></div>
    </div>
    <section className="cg-related-wrap"><div className="cg-related"><h2 className="cg-section-title">You Might Also Like</h2><div className="cg-related-grid">{RELATED.map(item=><article className="cg-related-card" key={item.title}><Link href={item.href} className="cg-related-category">{item.category}</Link><Link href={item.href} className="cg-related-title">{item.title} <span aria-hidden="true">›</span></Link><p className="cg-related-date">{item.date}</p></article>)}</div></div></section>
    <section className="cg-authors"><div><h2 className="cg-section-title">Meet the Authors</h2><p className="cg-authors-text">Connect with and discover our Today’s Harvest blog authors and their broad range of financial and northeast agricultural expertise.</p></div><Link href={AUTHORS_PATH} className="cg-button cg-authors-button">Meet the Authors</Link></section>
    <section className="cg-newsletter"><h2>Sign up for our Today&apos;s Harvest Blog.</h2><p>Get the latest blog articles delivered to your inbox.</p><form className="cg-form"><div className="cg-group"><label className="cg-label" htmlFor="email">Enter your email*</label><input id="email" className="cg-email" type="email" placeholder="email@address.com" required/><div className="cg-required">*Required Field</div></div><button className="cg-signup" type="submit">Sign Up</button></form></section>
  </main></>;
}
