"use client";

import Link from "next/link";
import HeroCarousel from "@/components/HeroCarousel";
import WhyUsCarousel from "@/components/WhyUsCarousel";

const BLOG = [
  { tag: "Business Tips and Tools", title: "A Smarter Safety Net: What the New USDA Payment Rules Mean for Your Farm", date: "June 30, 2026", href: "/resources/blog/260630NewUSDAPaymentRulesForYourFarm", body: "New USDA payment rules could have an important impact on farm operations. Here’s what producers should know and how proactive planning can help." },
  { tag: "Tax Talks", title: "Highlights from the Fiscal Year 2026-2027 NYS Budget", date: "June 4, 2026", href: "/resources/blog/260604FarmHighlightsNYSBudget" },
  { tag: "Tax Talks", title: "Research & Development Tax Credits for Farms: A Case Study", date: "April 22, 2026", href: "/resources/blog/260422ResearchDevelopmentTaxCreditsForFarms" },
  { tag: "Press Releases", title: "Farm Funding Reports Strong 2025 Financial Results", date: "March 23, 2026", href: "/about/NewsRoom/press-releases/260323-FarmCreditEastReportsStrong2025FinancialResults" },
];

const TRENDS = [
  { tag: "Industry Trends", title: "New Workforce Opportunities for Year-Round Dairy Operations", date: "June 2026", href: "/resources/trends" },
  { tag: "Industry Trends", title: "Understanding Today's Agricultural Labor Market", date: "May 2026", href: "/resources/trends" },
  { tag: "Business Tips and Tools", title: "Planning Ahead for Your Farm's Next Season", date: "April 2026", href: "/resources/trends" },
  { tag: "Industry Trends", title: "What Changing Markets Mean for Agricultural Producers", date: "March 2026", href: "/resources/trends" },
];

export default function Home() {
  const [feature, ...rest] = BLOG;
  const [tFeature, ...tRest] = TRENDS;
  return (
    <>
      <section className="grid w-full grid-cols-1 md:grid-cols-2 md:min-h-[690px]"><div className="flex items-center bg-white px-[4.05%] py-[36px] md:py-[65px] lg:py-[70px]"><div className="max-w-[700px]"><h1 className="m-0 max-w-[750px] font-display text-[32px] font-normal leading-[1.15] text-[#4f832a] sm:text-[36px] md:text-[40px] lg:text-[50px]">Discover an ag lender that works for you.</h1><p className="m-0 mt-[20px] max-w-[650px] text-[17px] leading-[27px] text-[#231f20] lg:text-[19px] lg:leading-[31px]">Farm Funding is made in agriculture - a cooperative owned by the customers it serves. More than any other lender, we understand your unique credit needs and offer the specialized products, tools and services to help grow your success.</p><div className="mt-[24px] flex flex-wrap gap-[12px]"><Link href="/financing" className="inline-flex h-[51px] items-center justify-center rounded-[4px] border-2 border-[#496d83] bg-[#496d83] px-[20px] text-[16px] font-bold text-white hover:bg-white hover:text-[#496d83]">Explore Financing</Link><Link href="/services" className="inline-flex h-[51px] items-center justify-center rounded-[4px] border-2 border-[#496d83] bg-[#496d83] px-[20px] text-[16px] font-bold text-white hover:bg-white hover:text-[#496d83]">View Services</Link></div></div></div><HeroCarousel className="relative h-[220px] md:h-[500px] lg:h-[645px]" /></section>
      <section className="grid w-full grid-cols-1 divide-y divide-white bg-[#e8ebef] md:grid-cols-2 md:divide-x md:divide-y-0"><div className="flex items-start gap-[22px] px-[4.05%] py-[32px] md:py-[45px]"><img src="/images/homepage/2026 AgViews Calendar Cover.jpg" alt="2026 AgViews Calendar" className="h-[115px] w-[155px] object-cover"/><div><h3 className="font-display text-[20px] font-bold">Calendar Photo Contest</h3><p className="mt-[10px] text-[16px] leading-[25px]">Submit your photo(s) of modern agriculture, fishing and forestry by July 31 for a chance to win $100!</p><Link href="/resources/Calendar-Photo-Contest" className="mt-[10px] inline-block font-bold text-[#705600]">Learn more ›</Link></div></div><div className="flex items-start gap-[22px] px-[4.05%] py-[32px] md:py-[45px]"><img src="/images/homepage/Appreciation Sign.png" alt="Customer appreciation event" className="h-[115px] w-[155px] object-cover"/><div><h3 className="font-display text-[20px] font-bold">2026 Customer Appreciation Events</h3><p className="mt-[10px] text-[16px] leading-[25px]">As a cooperative, our customers are at the core of everything we do. We hope you&apos;ll join us at an event this summer to show our appreciation.</p><Link href="/resources/events" className="mt-[10px] inline-block font-bold text-[#705600]">Learn more ›</Link></div></div></section>
      <section className="w-full bg-[#ecf1e4] px-[4.05%] py-[60px] lg:py-[75px]"><h2 className="font-display text-[32px] font-bold text-[#4f832a] lg:text-[40px]">Latest News &amp; Blog</h2><div className="mt-[30px] grid grid-cols-1 gap-[45px] md:grid-cols-2"><Link href={feature.href} className="group block"><img src="/images/homepage/Megan Clancy spotlight.jpg" alt="Featured agricultural story" className="block h-[300px] w-full object-cover lg:h-[350px]"/><div className="bg-[#4f832a] px-[28px] py-[25px] text-white"><span className="mb-[16px] inline-block border border-white/60 px-[10px] py-[5px] text-[13px] font-bold uppercase">{feature.tag}</span><h3 className="font-display text-[25px] font-bold leading-[32px]">{feature.title} ›</h3>{feature.body && <p className="mt-[15px] text-[16px] leading-[25px]">{feature.body}</p>}<span className="mt-[18px] block text-[13px] font-bold uppercase">{feature.date}</span></div></Link><div className="flex flex-col">{rest.map((post) => <Link key={post.title} href={post.href} className="group border-b border-[#d4d8d0] py-[22px]"><span className="mb-[12px] inline-block border border-[#231f20]/40 bg-white px-[10px] py-[5px] text-[13px] font-bold uppercase">{post.tag}</span><h4 className="font-display text-[22px] font-bold leading-[29px] text-[#705600] group-hover:text-[#496d83]">{post.title} ›</h4><span className="mt-[12px] block text-[13px] font-bold uppercase text-[#686868]">{post.date}</span></Link>)}<Link href="/resources/blog" className="mt-[20px] inline-flex h-[51px] w-fit items-center rounded-[4px] bg-[#496d83] px-[22px] font-bold text-white">View More</Link></div></div></section>
      <section className="w-full bg-white px-[4.05%] py-[60px] lg:py-[75px]"><h2 className="text-center font-display text-[32px] font-bold text-[#4f832a] lg:text-[40px]">No other lender delivers more for your money</h2><div className="mt-[30px]"><WhyUsCarousel /></div></section>
      <section className="w-full bg-[#ecf1e4] px-[4.05%] py-[60px] lg:py-[75px]"><h2 className="font-display text-[32px] font-bold text-[#4f832a] lg:text-[40px]">Industry Trends &amp; Education</h2><div className="mt-[30px] grid grid-cols-1 gap-[45px] md:grid-cols-2"><Link href={tFeature.href} className="group block"><img src="/images/homepage/Dairy cows milking.jpg" alt="Dairy cows being milked" className="block h-[300px] w-full object-cover lg:h-[350px]"/><div className="bg-[#4f832a] px-[28px] py-[25px] text-white"><span className="mb-[16px] inline-block border border-white/60 px-[10px] py-[5px] text-[13px] font-bold uppercase">{tFeature.tag}</span><h3 className="font-display text-[25px] font-bold leading-[32px]">{tFeature.title} ›</h3><p className="mt-[15px] text-[16px] leading-[25px]">A new USCIS policy is opening the door for dairy producers to access the H-2A temporary agricultural worker program, a workforce option that has long been out of reach for year-round dairy operations.</p><span className="mt-[18px] block text-[13px] font-bold uppercase">{tFeature.date}</span></div></Link><div className="flex flex-col">{tRest.map((post) => <Link key={post.title} href={post.href} className="group border-b border-[#d4d8d0] py-[22px]"><span className="mb-[12px] inline-block border border-[#231f20]/40 bg-white px-[10px] py-[5px] text-[13px] font-bold uppercase">{post.tag}</span><h4 className="font-display text-[22px] font-bold leading-[29px] text-[#705600]">{post.title} ›</h4><span className="mt-[12px] block text-[13px] font-bold uppercase text-[#686868]">{post.date}</span></Link>)}<Link href="/resources/trends" className="mt-[20px] inline-flex h-[51px] w-fit items-center rounded-[4px] bg-[#496d83] px-[22px] font-bold text-white">View More</Link></div></div></section>
    </>
  );
}
