import type { Metadata } from "next";
import Link from "next/link";

const DATA: Record<string, { title: string; intro: string; bullets: string[] }> = {
  "farmstart-seed-capital": { title: "FarmStart Seed Capital", intro: "A program designed to help eligible beginning farmers access capital as they establish or expand an agricultural business.", bullets: ["Designed for eligible beginning producers", "Can help bridge early-stage capital needs", "Program requirements apply"] },
  "young-beginning-small-veteran-farmer-incentives": { title: "Young, Beginning, Small and Veteran Farmer Incentives", intro: "Special financing incentives can help eligible producers entering or growing an agricultural business.", bullets: ["Potential fee or pricing advantages", "Support for qualifying producers", "Eligibility and program conditions apply"] },
  "generationnext": { title: "GenerationNext", intro: "Education and leadership support for the next generation of agricultural business owners and managers.", bullets: ["Build business and leadership skills", "Prepare for ownership and transition", "Connect with other emerging agricultural leaders"] },
  "harvesting-a-profit": { title: "Harvesting a Profit", intro: "A program focused on helping eligible beginning farmers strengthen financial and management skills.", bullets: ["Build financial-management knowledge", "Strengthen business planning", "Support long-term farm success"] },
};
function titleFromSlug(slug: string) { return slug.replace(/-/g, " ").replace(/\b\w/g, (m) => m.toUpperCase()); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; return { title: `${DATA[slug]?.title ?? titleFromSlug(slug)} | Farm Funding` }; }
export default async function BeginningFarmerProgramPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const d = DATA[slug] ?? { title: titleFromSlug(slug), intro: "Explore beginning farmer financing and education resources.", bullets: ["Review eligibility", "Learn about available programs", "Contact your local Farm Funding office"] }; return <main><section className="bg-cream mt-8 px-[4%] py-16 md:py-20"><div className="max-w-5xl mx-auto"><p className="text-xs font-bold uppercase tracking-[0.16em] text-grey-text">Beginning Farmer Programs</p><h1 className="mt-3 font-display text-4xl md:text-[52px] font-extrabold text-forest">{d.title}</h1><p className="mt-5 max-w-3xl text-lg text-charcoal/80 leading-relaxed">{d.intro}</p></div></section><section className="px-[4%] py-14 md:py-18"><div className="max-w-5xl"><h2 className="font-display text-3xl font-bold text-forest">Program highlights</h2><ul className="mt-7 list-disc pl-6 space-y-3 text-base text-charcoal/80">{d.bullets.map((b) => <li key={b}>{b}</li>)}</ul><Link href="/contact" className="mt-8 inline-flex px-7 py-3.5 bg-clay text-white text-sm font-bold rounded-sm">Contact My Office</Link></div></section><section className="bg-forest-dark text-white text-center px-[4%] py-14"><h2 className="font-display text-3xl font-bold text-white">Explore all Beginning Farmer Programs</h2><Link href="/financing/beginning-farmer-programs" className="mt-7 inline-flex px-7 py-3.5 border-2 border-white text-white font-bold rounded-sm">View Programs</Link></section></main>; }
